/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB4M10
 */
public class Principal_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Principal_GUI
     */
    public Principal_GUI() {
        initComponents();
        Pedra.setVisible(false);
        Papel.setVisible(false);
        Tesoura.setVisible(false);
        Pedra1.setVisible(false);
        Papel1.setVisible(false);
        Tesoura1.setVisible(false);
        
    }
    int cont = 0;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tesoura = new org.edisoncor.gui.panel.PanelImage();
        Pedra = new org.edisoncor.gui.panel.PanelImage();
        Papel = new org.edisoncor.gui.panel.PanelImage();
        Pedra1 = new org.edisoncor.gui.panel.PanelImage();
        Papel1 = new org.edisoncor.gui.panel.PanelImage();
        Tesoura1 = new org.edisoncor.gui.panel.PanelImage();
        jogar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOKENPO");

        jPanel1.setLayout(null);

        Tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout TesouraLayout = new javax.swing.GroupLayout(Tesoura);
        Tesoura.setLayout(TesouraLayout);
        TesouraLayout.setHorizontalGroup(
            TesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        TesouraLayout.setVerticalGroup(
            TesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Tesoura);
        Tesoura.setBounds(40, 90, 70, 70);

        Pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pedra.png"))); // NOI18N

        javax.swing.GroupLayout PedraLayout = new javax.swing.GroupLayout(Pedra);
        Pedra.setLayout(PedraLayout);
        PedraLayout.setHorizontalGroup(
            PedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        PedraLayout.setVerticalGroup(
            PedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel1.add(Pedra);
        Pedra.setBounds(40, 160, 68, 68);

        Papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/papel.png"))); // NOI18N

        javax.swing.GroupLayout PapelLayout = new javax.swing.GroupLayout(Papel);
        Papel.setLayout(PapelLayout);
        PapelLayout.setHorizontalGroup(
            PapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        PapelLayout.setVerticalGroup(
            PapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jPanel1.add(Papel);
        Papel.setBounds(40, 230, 66, 65);

        Pedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pedra.png"))); // NOI18N

        javax.swing.GroupLayout Pedra1Layout = new javax.swing.GroupLayout(Pedra1);
        Pedra1.setLayout(Pedra1Layout);
        Pedra1Layout.setHorizontalGroup(
            Pedra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        Pedra1Layout.setVerticalGroup(
            Pedra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel1.add(Pedra1);
        Pedra1.setBounds(460, 160, 68, 68);

        Papel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/papel.png"))); // NOI18N

        javax.swing.GroupLayout Papel1Layout = new javax.swing.GroupLayout(Papel1);
        Papel1.setLayout(Papel1Layout);
        Papel1Layout.setHorizontalGroup(
            Papel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        Papel1Layout.setVerticalGroup(
            Papel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jPanel1.add(Papel1);
        Papel1.setBounds(460, 230, 66, 65);

        Tesoura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout Tesoura1Layout = new javax.swing.GroupLayout(Tesoura1);
        Tesoura1.setLayout(Tesoura1Layout);
        Tesoura1Layout.setHorizontalGroup(
            Tesoura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Tesoura1Layout.setVerticalGroup(
            Tesoura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(Tesoura1);
        Tesoura1.setBounds(460, 90, 70, 70);

        jogar1.setText("Jogar");
        jogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jogar1);
        jogar1.setBounds(200, 290, 149, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(573, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogar1ActionPerformed
        
        
        do {
        Random gerador = new Random();
        int maquina = gerador.nextInt(3);
        String x = JOptionPane.showInputDialog(null, "[0] - Pedra\n"
                + "[1] - Papel\n"
                + "[2] - Tesoura");
       int jogador = Integer.parseInt(x);
        
        if(maquina == 0 && jogador == 1){
            Pedra.setVisible(true);
            Papel1.setVisible(true);
            JOptionPane.showMessageDialog(null, "Parabéns VITORIA");
            cont = 1;
        }
        else if(maquina == 1 && jogador == 2){
            Papel.setVisible(true);
            Tesoura1.setVisible(true);
            JOptionPane.showMessageDialog(null, "Parabéns VITORIA");
            cont = 1;
        }
        else if(maquina == 2 && jogador == 0){
            Tesoura.setVisible(true);
            Pedra1.setVisible(true);
            JOptionPane.showMessageDialog(null, "Parabéns VITORIA");
            cont = 1;
        }
        else if(maquina == jogador){
            JOptionPane.showMessageDialog(null, "Empate Tente Novamente");
            switch(maquina){
                case 0:
                    Pedra.setVisible(true);
                case 1:
                    Papel.setVisible(true);
                case 2:
                    Tesoura.setVisible(true);
            }
            switch(jogador){
                case 0:
                    Pedra1.setVisible(true);
                case 1:
                    Papel1.setVisible(true);
                case 2:
                    Tesoura1.setVisible(true);
            }
            cont = 1;
        }
        else{
            switch(maquina){
                case 0:
                    Pedra.setVisible(true);
                case 1:
                    Papel.setVisible(true);
                case 2:
                    Tesoura.setVisible(true);
            }
            switch(jogador){
                case 0:
                    Pedra1.setVisible(true);
                case 1:
                    Papel1.setVisible(true);
                case 2:
                    Tesoura1.setVisible(true);
            }
            JOptionPane.showMessageDialog(null, "Você Perdeu! Tente Novamente");
        }
        
        Pedra.setVisible(false);
        Papel.setVisible(false);
        Tesoura.setVisible(false);
        Pedra1.setVisible(false);
        Papel1.setVisible(false);
        Tesoura1.setVisible(false);
        } while (cont == 0);
        
    }//GEN-LAST:event_jogar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage Papel;
    private org.edisoncor.gui.panel.PanelImage Papel1;
    private org.edisoncor.gui.panel.PanelImage Pedra;
    private org.edisoncor.gui.panel.PanelImage Pedra1;
    private org.edisoncor.gui.panel.PanelImage Tesoura;
    private org.edisoncor.gui.panel.PanelImage Tesoura1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jogar1;
    // End of variables declaration//GEN-END:variables
}
