/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB4M10
 */
public class Principal_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Principal_GUI
     */
    public Principal_GUI() {
        initComponents();
        PedraPC.setVisible(false);
        PapelPC.setVisible(false);
        TesouraPC.setVisible(false);
        PedraUser.setVisible(false);
        PapelUser.setVisible(false);
        TesouraUser.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TesouraPC = new org.edisoncor.gui.panel.PanelImage();
        PedraPC = new org.edisoncor.gui.panel.PanelImage();
        PapelPC = new org.edisoncor.gui.panel.PanelImage();
        PedraUser = new org.edisoncor.gui.panel.PanelImage();
        PapelUser = new org.edisoncor.gui.panel.PanelImage();
        TesouraUser = new org.edisoncor.gui.panel.PanelImage();
        jogar1 = new javax.swing.JButton();
        TextResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOKENPO");

        jPanel1.setLayout(null);

        TesouraPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout TesouraPCLayout = new javax.swing.GroupLayout(TesouraPC);
        TesouraPC.setLayout(TesouraPCLayout);
        TesouraPCLayout.setHorizontalGroup(
            TesouraPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        TesouraPCLayout.setVerticalGroup(
            TesouraPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(TesouraPC);
        TesouraPC.setBounds(40, 90, 70, 70);

        PedraPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pedra.png"))); // NOI18N

        javax.swing.GroupLayout PedraPCLayout = new javax.swing.GroupLayout(PedraPC);
        PedraPC.setLayout(PedraPCLayout);
        PedraPCLayout.setHorizontalGroup(
            PedraPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        PedraPCLayout.setVerticalGroup(
            PedraPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel1.add(PedraPC);
        PedraPC.setBounds(40, 160, 68, 68);

        PapelPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/papel.png"))); // NOI18N

        javax.swing.GroupLayout PapelPCLayout = new javax.swing.GroupLayout(PapelPC);
        PapelPC.setLayout(PapelPCLayout);
        PapelPCLayout.setHorizontalGroup(
            PapelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        PapelPCLayout.setVerticalGroup(
            PapelPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jPanel1.add(PapelPC);
        PapelPC.setBounds(40, 230, 66, 65);

        PedraUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pedra.png"))); // NOI18N

        javax.swing.GroupLayout PedraUserLayout = new javax.swing.GroupLayout(PedraUser);
        PedraUser.setLayout(PedraUserLayout);
        PedraUserLayout.setHorizontalGroup(
            PedraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        PedraUserLayout.setVerticalGroup(
            PedraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel1.add(PedraUser);
        PedraUser.setBounds(460, 160, 68, 68);

        PapelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/papel.png"))); // NOI18N

        javax.swing.GroupLayout PapelUserLayout = new javax.swing.GroupLayout(PapelUser);
        PapelUser.setLayout(PapelUserLayout);
        PapelUserLayout.setHorizontalGroup(
            PapelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        PapelUserLayout.setVerticalGroup(
            PapelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        jPanel1.add(PapelUser);
        PapelUser.setBounds(460, 230, 66, 65);

        TesouraUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout TesouraUserLayout = new javax.swing.GroupLayout(TesouraUser);
        TesouraUser.setLayout(TesouraUserLayout);
        TesouraUserLayout.setHorizontalGroup(
            TesouraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        TesouraUserLayout.setVerticalGroup(
            TesouraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(TesouraUser);
        TesouraUser.setBounds(460, 90, 70, 70);

        jogar1.setText("Jogar");
        jogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jogar1);
        jogar1.setBounds(200, 290, 149, 30);
        jPanel1.add(TextResultado);
        TextResultado.setBounds(170, 140, 210, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(573, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogar1ActionPerformed
       
        PedraPC.setVisible(false);
        PapelPC.setVisible(false);
        TesouraPC.setVisible(false);
        PedraUser.setVisible(false);
        PapelUser.setVisible(false);
        TesouraUser.setVisible(false);
        
        Random gerador = new Random();
        int maquina = gerador.nextInt(2) + 0;
        String x = JOptionPane.showInputDialog(null, "[0] - Pedra\n"
                + "[1] - Papel\n"
                + "[2] - Tesoura");
       int jogador = Integer.parseInt(x);
        
        switch(maquina){
                case 0:
                    PedraPC.setVisible(true);
                    PapelPC.setVisible(false);
                    TesouraPC.setVisible(false);
                case 1:
                    PedraPC.setVisible(false);
                    PapelPC.setVisible(true);
                    TesouraPC.setVisible(false);
                case 2:
                    PedraPC.setVisible(false);
                    PapelPC.setVisible(false);
                    TesouraPC.setVisible(true);
            }
            switch(jogador){
                case 0:
                    PedraUser.setVisible(true);
                    PapelUser.setVisible(false);
                    TesouraUser.setVisible(false);
                case 1:
                    PedraUser.setVisible(false);
                    PapelUser.setVisible(true);
                    TesouraUser.setVisible(false);
                case 2:
                    PedraUser.setVisible(false);
                    PapelUser.setVisible(false);
                    TesouraUser.setVisible(true);
            }
        if(maquina == 0 && jogador == 1){
            TextResultado.setText("Parabéns Vitoria !!!");
        }else if(maquina == 1 && jogador == 2){
            TextResultado.setText("Parabéns Vitoria !!!");
        }else if(maquina == 2 && jogador == 0){
            TextResultado.setText("Parabéns Vitoria !!!"); 
        }else if(maquina == jogador){
            TextResultado.setText("Empate Tente Novamente");
        }else{
            TextResultado.setText("Voce perdeu Tente Novamente !!!");
            }
        
        
    }//GEN-LAST:event_jogar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage PapelPC;
    private org.edisoncor.gui.panel.PanelImage PapelUser;
    private org.edisoncor.gui.panel.PanelImage PedraPC;
    private org.edisoncor.gui.panel.PanelImage PedraUser;
    private org.edisoncor.gui.panel.PanelImage TesouraPC;
    private org.edisoncor.gui.panel.PanelImage TesouraUser;
    private javax.swing.JLabel TextResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jogar1;
    // End of variables declaration//GEN-END:variables
}
